name: CI
on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.*
jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        target: x86_64-unknown-linux-musl
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - run: sudo apt-get install -y musl-tools
    - run: cargo +nightly build --release --locked --target x86_64-unknown-linux-musl

    - name: Upload binary to commit artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sysalert-${{ github.ref_name }}-x86_64-unknown-linux-musl
        path: target/x86_64-unknown-linux-musl/release/sysalert
        retention-days: 7

    - uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        file: target/x86_64-unknown-linux-musl/release/sysalert
        asset_name: sysalert-$tag-x86_64-unknown-linux-musl
        tag: ${{ github.ref }}
