name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-musl
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: sudo apt-get install -y musl-tools
    - run: cargo build --release --locked --target x86_64-unknown-linux-musl
    - run: echo "VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
    - uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/x86_64-unknown-linux-musl/release/sysalert
        asset_name: sysalert-${{ env.VERSION }}-x86_64-unknown-linux-musl
        tag: ${{ github.ref }}
