name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: cargo build --release --locked
    - uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/sysalert
        asset_name: sysalert-${{ github.ref }}-x86_64-unknown-linux-gnu
        tag: ${{ github.ref }}
